### ISSUE TITLE
Direction of this project: More high-level interface desired?

### ISSUE THREAD

**Issue by mfherbst** [unkcpz/Libxc.jl#4]
@unkcpz thanks for starting this project. I've been meaning to code up a nice Julia wrapper around Libxc for quite some time myself as well, but haven't really managed to get properly started. Since I am currently working on a Julia-based density-functional theory code, [DFTK.jl](https://github.com/mfherbst/DFTK.jl), I would enjoy to have some high-level sugar around the ugly `ccall`s as well to hide the details from our user code.

I already made an attempt at this before, but never managed to turn this into a proper package. Today I picked up my pieces and integrated my efforts into your code. Feel free to take a look at my branch: [mfherbst/Libxc.jl](https://github.com/mfherbst/Libxc.jl/tree/higher_level_interface). 

I am not sure what direction you plan to go with this project, but if you intend to add a more  high-level interface in the direction I have sketched in my code, I am very happy to convert this into a proper PR and add a few tests. Of course if you have any comments or suggestions with respect to my code, please let me know.

**Comment by unkcpz** [comment]
> Since I am currently working on a Julia-based density-functional theory code, DFTK.jl,

I also have a idea to craete a julia-based DFT code, and have tried [Jbinit](https://github.com/unkcpz/Jbinit.jl) before I find the project [f-fathurrahman/PWDFT.jl](https://github.com/f-fathurrahman/PWDFT.jl). I make Libxc.jl to get rid of ugly `ccall` in his code.

 > Today I picked up my pieces and integrated my efforts into your code.

> but if you intend to add a more high-level interface in the direction I have sketched in my code, I am very happy to convert this into a proper PR and add a few tests. 

I want to have some high-level interface, thanks! But I think it need to be clearly separated from the wrapper code and have comprehensive unittest coverage. 
Any PR is welcome. Or maybe we can create a team and hold the code there, so that you can modified the code directly?

> I am not sure what direction you plan to go with this project, 

I have the same intention as you make a own DFT code. Therefore, our direction about this project should not diverge too much. The most important problem is that do we need working on DFT code separately? 
To my knowledge, the framework of DFT code is similar. Maybe we can have a more detailed discussion?
My plan is to have a DFT code under the framework of [DFT++ formalism](http://jdftx.org/PracticalDFT.html), so that new algorithms and new physics can be easily added.

**Comment by mfherbst** [comment]
I have opened PR #5 with my changes, where we can discuss the details about the interface.

Regarding the DFT code and DFT projects, I am very happy to discuss directions. I am aware of [f-fathurrahman/PWDFT.jl](https://github.com/f-fathurrahman/PWDFT.jl) and took a look at it before working on DFTK. If I get it right, the difference in direction is that DFTK intends to facilitate especially low-level algorithmic development like SCF algorithms or numerics over a readily usable solution to run calculations. For this reason we try to push as much as possible to existing external packages and keep the code base as minimalistic as possible. Part of that is, that DFTK by itself is not that useful. It can, however, be easily combined with other packages to get something going. For example we rely on [pymatgen](https://pymatgen.org) to setup our crystal and lattices. See [silicon_noXC.jl](https://github.com/mfherbst/DFTK.jl/blob/master/examples/silicon_noXC.jl) as an example how this works in practice. Our initial focus will thus not be to provide many features, but to be a flexible and modular.

I am not of the youtube series you mention, but generally speaking the ability to incorporate new physics in a simple way would be part of the aspired goals of DFTK as well. I'll take a look at it.

**Comment by mfherbst** [comment]
Closing this, since PR #5 is merged.
